openapi: 3.0.0
info:
  title: Calculator API
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /:
    get:
      summary: Health Check
      responses:
        "200":
          description: Calculator App is running
  /api/v1/add:
    post:
      summary: Add two numbers
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                  format: int
                b:
                  type: number
                  format: int
      responses:
        "200":
          description: Successfully added two numbers
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: int
  /api/v1/subtract:
    post:
      summary: Subtract two numbers
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                  format: int
                b:
                  type: number
                  format: int
      responses:
        "200":
          description: Successfully subtracted two numbers
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: int
  /api/v1/multiply:
    post:
      summary: Multiply two numbers
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                  format: int
                b:
                  type: number
                  format: int
      responses:
        "200":
          description: Successfully multiplied two numbers
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: int
  /api/v1/divide:
    post:
      summary: Divide two numbers
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                dividend:
                  type: number
                  format: int
                divisor:
                  type: number
                  format: int
      responses:
        "200":
          description: Successfully divided two numbers
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: int

  /api/v1/sum:
    post:
      summary: Add all numbers in an array
      security:
      - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
                format: int

      responses:
        "200":
          description: Successfully divided two numbers
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    format: int
