@baseUrl = http://localhost:8080/api/v1

### Add
POST {{baseUrl}}/add
Content-Type: application/json

{
    "a": 1.11111,
    "b": 2.327832
}

### Subtract
POST {{baseUrl}}/subtract
Content-Type: application/json

{
    "a": 1,
    "b": 2
}

### Multiply
POST {{baseUrl}}/multiply
Content-Type: application/json

{
    "a": 5,
    "b": 2
}

### Divide
POST {{baseUrl}}/divide
Content-Type: application/json

{
    "dividend": 10,
    "divisor": 3
}

### Divide - division by zero
POST {{baseUrl}}/divide
Content-Type: application/json

{
    "dividend": 10,
    "divisor": 0
}

### Sum
POST {{baseUrl}}/sum
Content-Type: application/json

[2, 3, 5, 7]
